name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'protos/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.17.3'

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run Makefile
        run: |
        go get -u github.com/ckaznocha/protoc-gen-lint
        go get -u google.golang.org/grpc
        go get -u github.com/golang/protobuf/protoc-gen-go
        make
