name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'protos/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.17.3'

      - name: Run Make
        run: make
